
server:
  port: 8081

spring:
  profiles:
    include:
      - core
      - http

  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password

#logging:
#  level:
#    root: debug
